version: 2

models:
  - name: stg_players
    description: Cleaned player data
    columns:
      - name: player_tag
        description: Unique identifier

  - name: stg_attacks
    description: Raw attacks cleaned and normalized
    columns:
      - name: attacker_tag
        description: Who attacked
      - name: stars
        description: Stars earned

  - name: stg_participation
    description: War participation details
    columns:
      - name: player_tag
        description: The player
      - name: in_war
        description: Whether they were marked for war
